FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY data/ ./data/

# Ajout de tous les fichiers nécessaires
COPY api/main.py ./api/main.py
COPY api/wait_for_model.py ./api/wait_for_model.py

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
