# Base image
FROM python:3.10-slim

# Dossier de travail
WORKDIR /app

# Copie des fichiers nécessaires
COPY requirements.txt .
COPY api/ ./api/
COPY data/ ./data/
COPY api/wait_for_model.py ./api/wait_for_model.py

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port de l'API
EXPOSE 8000

# Lancer l'API FastAPI
CMD ["python", "api/wait_for_model.py"] 