[api]
ml-api ansible_host=54.173.184.37

[training]
ml-training ansible_host=35.173.135.85


[training:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/labsuser.pem

[api:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/labsuser.pem